name: CI
on:  
  push:
    branches:
      - dev
jobs:
  build:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy
